export const lifeQuotes: string[] = [
  "Happiness comes with a lot of pain, if you do not feel that pain… it means someone else is bearing that pain for you.",
  "Just because you love oceans, doesn't mean you have to drown in it.",
  "Moon is only beautiful because it's far.",
  "The fears we don't face become our limit.",
  "Your value is determined by how much you can provide. Even your parents will leave if you provide nothing.",
  "Biting your tongue accidentally is the perfect example of messing up even after having years of perfection.",
  "Maybe dreams always end when you're at the good part because you're supposed to make it a reality.",
  "Water has no effect on fake flowers.",
  "Your thoughts can be your biggest enemies. Make friends with them.",
  "Be devoted to one another in love. Honor one another above yourself.",
  "What you can do should never be your limit.",
  "If you pray for flowers, don't be surprised when it starts raining.",
  "Until death, all defeats are psychological.",
  "You live to be temporary, you work hard to become permanent.",
  "If you hang out with me for too long, then I'll brainwash you into thinking you can achieve anything and everything.",
  "The rearview is for glancing, not staring.",
  "The man who likes walking will walk further than the man who loves the destination.",
  "It's okay, sometimes you expect a lot from someone because you'd do just as much for them.",
  "Water that is too pure has no fish.",
  "If you want to know the value of something, ask the one who craves it.",
  "It is impossible for a man to learn what he thinks he already knows.",
  "The one who learns to think will never be the one who refuses to learn what he thinks he already knows.",
  "The ability to observe without judgment is the highest form of intelligence.",
  "Just because I carry it well, doesn't mean it is not heavy.",
  "No matter how much you blame others for your problems, they are still yours to solve.",
  "Change happens when the pain of staying the same is greater than the pain of changing.",
  "Your lack of commitment is an insult to everyone who believed in you.",
  "Knowledge is the most expensive asset.",
  "Reality is a product of chance that we call fate. We can't predict it.",
  "Mistake is another word for experience. It's a shortcut to wisdom.",
  "History doesn't always tell us the whole truth. People change the past to fit what they want to see.",
  "A candle loses nothing when used to light another.",
  "If you do too much for people, they start loving your hand, not your heart.",
  "Change but never replace.",
  "Don't compete, dominate.",
  "I helped a person climb a mountain and I found that I too had reached the top.",
  "Biggest risk is that you don't take any risk.",
  "When someone is drowning, that is not the time to teach them how to swim.",
  "Never cross oceans for someone who won't even cross a puddle for you.",
  "You need to touch the book in order to turn pages.",
  "Big things have small beginnings.",
  "What something is, is not the same as what it means.",
  "Your life is always moving in the direction of your strongest thoughts.",
  "You're acting like you're about to lose the game while the game is still going on.",
  "Don't take criticism from the people who you can't get advice from.",
  "Always help your closest ones and the ones who you'll never meet.",
  "You can't control which bird flies over your head, but you decide whether it makes a nest on your head or not (thought is a bird).",
  "Creativity cannot exist when pressure exists.",
  "When spirit breaks, body follows.",
  "Heal the body and spirit will follow.",
  "Don't look at money for too long. It's Medusa.",
  "Solve the current problem simply. Don't build future problems today.",
  "Summer is only beautiful when you know Winter is coming.",
  "When the body suffers, spirit blooms.",
  "Knowledge is not free, you have to pay attention.",
  "There is no trap so deadly as the trap you set for yourself.",
  "Existence is a series of absurdities leading to infinite nothingness.",
];
